CREATE TABLE CLIENTE(
      ID INTEGER PRIMARY KEY AUTO_INCREMENT,
      PRIMEIRO_NOME VARCHAR(100)  NOT NULL,
      ULTIMO_NOME VARCHAR(100) NOT NULL,
      TELEFONE VARCHAR(20) NOT NULL,
      CPF VARCHAR(11) NOT NULL,
      IDADE VARCHAR(3) NOT NULL
);

